spring:
  application:
    name: api-gateway
server:
  port: ${SERVER_PORT:8082}
gateway:
  targets:
    core: ${CORE_SERVICE_URL:http://localhost:8080}
    social: ${SOCIAL_SERVICE_URL:http://localhost:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info
