package com.hustleup.common.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing an in-app notification delivered to a specific user.
 *
 * <p><b>What is a Notification?</b><br>
 * A notification is a short message generated by the platform when something of interest
 * happens — for example: "Your listing was favourited", "You have a new message", or
 * "Your order has shipped". Each notification targets exactly one user.
 *
 * <p><b>Why JPA/Hibernate?</b><br>
 * Persisting notifications to a relational table lets users read their notification history
 * even after a page refresh or app restart, and allows unread counts to be queried
 * efficiently via SQL aggregates (see {@link com.hustleup.common.repository.NotificationRepository}).
 *
 * <p><b>Table mapping:</b><br>
 * Maps to the {@code notifications} table. There is a logical many-to-one relationship
 * with the {@code users} table via the {@code user_id} column, but no JPA
 * {@code @ManyToOne} join is declared here — we store only the raw {@link UUID} to keep
 * the entity lightweight and avoid unnecessary cross-service joins in a microservices
 * architecture where the User entity might live in a different service's datasource.
 *
 * <p><b>Architecture note:</b><br>
 * The Notification service (or any service that needs to send notifications) depends on
 * {@code hustleup-common} to share this entity and its repository without code
 * duplication. The notification-sending logic lives in the calling service; this class is
 * purely the data model.
 */
@Entity                          // Declares this class as a JPA-managed persistent entity
@Table(name = "notifications")   // Maps to the "notifications" table in the database
@Getter @Setter                  // Lombok: generates getters and setters for all fields
@NoArgsConstructor               // Lombok: zero-arg constructor required by JPA
@AllArgsConstructor              // Lombok: all-fields constructor used internally by @Builder
@Builder                         // Lombok: fluent builder pattern for readable object creation
public class Notification {

    /**
     * Primary key — a UUID auto-generated at insert time.
     *
     * <p>Using UUID (rather than a sequential long) ensures that notification IDs are
     * globally unique across services and cannot be guessed. Hibernate handles generation
     * via {@code GenerationType.UUID}.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The ID of the user who should receive and see this notification.
     *
     * <p>This is a soft foreign key referencing {@code users.id}. We deliberately avoid a
     * hard JPA {@code @ManyToOne} association here to prevent Hibernate from lazy-loading
     * an entire User object every time we query notifications — we only need the ID for
     * filtering. The {@code nullable = false} constraint ensures every notification always
     * belongs to a user.
     */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /**
     * Short headline for the notification (e.g. "New message from Alice").
     *
     * <p>Shown prominently in the notification bell dropdown and notification centre.
     * Must always be present — {@code nullable = false}.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Full body text of the notification providing more detail.
     *
     * <p>{@code columnDefinition = "TEXT"} overrides the default VARCHAR column type,
     * allowing the message to be arbitrarily long — important for notifications that may
     * include a preview of a message body or a listing description.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    /**
     * A string tag categorising the kind of notification (e.g. "ORDER", "MESSAGE", "VOUCH").
     *
     * <p>Used on the frontend to display an appropriate icon or colour-code notification
     * items. Kept as a {@code String} rather than an enum so new types can be added
     * without a schema migration or recompile of this shared module.
     */
    @Column(name = "notification_type", nullable = false)
    private String notificationType;

    /**
     * Whether the user has already read / seen this notification.
     *
     * <p>Defaults to {@code false} (unread). Flipped to {@code true} when the user opens
     * their notification centre or explicitly marks it as read. The unread count is
     * efficiently queried using
     * {@link com.hustleup.common.repository.NotificationRepository#countByUserIdAndReadFalse}.
     *
     * <p>{@code @Builder.Default} is needed so the Lombok builder respects the
     * {@code false} initialiser; without it the builder would set the field to the
     * primitive default ({@code false} anyway, but explicit is clearer).
     */
    @Column(name = "is_read")
    @Builder.Default
    private boolean read = false; // New notifications are always unread until the user opens them

    /**
     * Optional ID linking this notification to a related entity in another service.
     *
     * <p>For example, a "New order" notification might store the order's UUID here so the
     * frontend can deep-link directly to the order detail page. A "New message"
     * notification might reference the conversation ID. {@code null} when the
     * notification is standalone with no linkable entity.
     */
    @Column(name = "reference_id")
    private UUID referenceId;

    /**
     * Timestamp of when this notification was created and dispatched.
     *
     * <p>Defaults to the current application time at object construction. Used for
     * ordering notifications chronologically (newest first) in the notification centre.
     */
    @Column(name = "created_at")
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
