spring:
  application:
    name: hustleup-notification
  datasource:
    url: jdbc:mysql://localhost:3306/hustleup?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        type:
          preferred_uuid_jdbc_type: VARCHAR

server:
  port: 8085

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
