/**
 * Spring Data JPA repository for {@link com.hustleup.social.model.Follow} entities.
 *
 * <p>The Follow entity's primary key is a surrogate UUID ({@code UUID}), but the
 * meaningful key is the composite ({@code follower_id}, {@code following_id}).
 * This repository provides the query methods needed to traverse the social graph.
 *
 * <h2>Social graph queries</h2>
 * The social graph is a directed graph:
 * <ul>
 *   <li>To find "who follows user X": query by {@code followingId = X}.</li>
 *   <li>To find "who X follows": query by {@code followerId = X}.</li>
 * </ul>
 * Both query patterns are supported here.
 *
 * <h2>Type parameters</h2>
 * {@code JpaRepository<Follow, UUID>} — the primary key type is {@link java.util.UUID}
 * because the Follow entity uses a UUID surrogate key (generated by the database).
 */
package com.hustleup.social.repository;

import com.hustleup.social.model.Follow;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.UUID;
import java.util.List;
import java.util.Optional;

public interface FollowRepository extends JpaRepository<Follow, UUID> {

    /**
     * Counts how many users follow the given user ("follower count").
     *
     * <p>Used to display "X followers" on a user's profile page.
     * Spring Data generates: {@code SELECT COUNT(*) FROM follows WHERE following_id = ?}
     *
     * @param followingId the UUID of the user whose follower count to calculate
     * @return the number of users who follow this user
     */
    int countByFollowingId(UUID followingId);

    /**
     * Counts how many users the given user follows ("following count").
     *
     * <p>Used to display "following Y" on a user's profile page.
     * Spring Data generates: {@code SELECT COUNT(*) FROM follows WHERE follower_id = ?}
     *
     * @param followerId the UUID of the user whose following count to calculate
     * @return the number of users this user follows
     */
    int countByFollowerId(UUID followerId);

    /**
     * Checks whether a specific follow relationship exists.
     *
     * <p>Used for idempotency checking in the follow endpoint (don't create duplicates)
     * and for the "is-following" check endpoint.
     * Spring Data generates an efficient EXISTS query.
     *
     * @param followerId  the UUID of the potential follower
     * @param followingId the UUID of the potentially followed user
     * @return true if the relationship exists, false otherwise
     */
    boolean existsByFollowerIdAndFollowingId(UUID followerId, UUID followingId);

    /**
     * Finds a specific follow relationship by the two user UUIDs.
     *
     * <p>Used by the unfollow endpoint to load the Follow row before deleting it.
     * Returns {@code Optional.empty()} if the relationship does not exist,
     * making the unfollow endpoint naturally idempotent.
     *
     * @param followerId  the UUID of the follower
     * @param followingId the UUID of the followed user
     * @return Optional containing the Follow entity, or empty if not found
     */
    Optional<Follow> findByFollowerIdAndFollowingId(UUID followerId, UUID followingId);

    /**
     * Returns all Follow records where the {@code following_id} matches.
     *
     * <p>In plain English: "returns all the follow relationships where user X is being followed"
     * — i.e., the list of users who follow X.
     * Used by the followers list endpoint and by new-post notification fanout.
     *
     * @param followingId the UUID of the user who is being followed
     * @return list of Follow entities representing the followers
     */
    List<Follow> findByFollowingId(UUID followingId);

    /**
     * Returns all Follow records where the {@code follower_id} matches.
     *
     * <p>In plain English: "returns all the follow relationships where user X is the follower"
     * — i.e., the list of users that X follows.
     * Used by the following list endpoint and by the recommendation engine's social-graph scoring.
     *
     * @param followerId the UUID of the user who is doing the following
     * @return list of Follow entities representing whom this user follows
     */
    List<Follow> findByFollowerId(UUID followerId);
}
