/**
 * JPA entity representing a directed follow relationship between two users.
 *
 * <p>A Follow record encodes "follower follows following" — user A (the follower)
 * has chosen to subscribe to updates from user B (the following).
 *
 * <h2>Table: {@code follows}</h2>
 * Each row is one directed edge in the user social graph.
 *
 * <h2>Unique constraint</h2>
 * {@code @UniqueConstraint(columnNames = {"follower_id", "following_id"})} ensures
 * the database will reject a duplicate follow (same follower, same target).
 * The application code also checks for duplicates before inserting, but the DB
 * constraint is the final safety net.
 *
 * <h2>Why Lombok @Data?</h2>
 * {@code @Data} generates: {@code equals()}, {@code hashCode()}, {@code toString()},
 * a constructor for all required fields, and getters/setters for every field.
 * This removes hundreds of lines of boilerplate.  Just be aware: {@code @Data} on JPA
 * entities can cause issues with Hibernate's proxy mechanism if {@code equals/hashCode}
 * are based on mutable fields — the auto-generated UUID primary key here is safe
 * because it's set by the DB and never changes.
 */
package com.hustleup.social.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

// Marks this class as a JPA-managed entity.
@Entity

// Table name and the composite unique constraint on (follower_id, following_id).
// The unique constraint prevents the same follow from being recorded twice at the DB level.
@Table(name = "follows", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"follower_id", "following_id"})
})

// @Data from Lombok: generates getters, setters, equals, hashCode, toString, and
// a required-args constructor. This is why there are no explicit getters/setters below.
@Data
public class Follow {

    /**
     * Surrogate primary key — a UUID generated by the database on insert.
     *
     * <p>{@code @GeneratedValue(strategy = GenerationType.UUID)} tells Hibernate to
     * use the database's UUID generation strategy (or its own UUID generator in newer
     * versions) rather than an auto-increment integer.  This gives globally unique IDs
     * safe for distributed use.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * UUID of the user who is doing the following (the "subscriber").
     *
     * <p>Combined with {@link #followingId} this forms the logical composite key of
     * the relationship, even though a surrogate {@link #id} is used as the primary key.
     */
    @Column(name = "follower_id", nullable = false)
    private UUID followerId;

    /**
     * UUID of the user being followed (the "content creator" / "followed account").
     *
     * <p>Together with {@link #followerId} this uniquely identifies one follow edge
     * in the social graph.  The {@code UNIQUE} constraint above enforces this.
     */
    @Column(name = "following_id", nullable = false)
    private UUID followingId;

    /**
     * Timestamp recording when the follow relationship was created.
     *
     * <p>Automatically set by Hibernate to the current time on insert.
     * {@code updatable = false} prevents modification after creation.
     * Useful for analytics (e.g. "how many new followers in the last 7 days?").
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
