spring:
  application:
    name: hustleup-gateway
  cloud:
    gateway:
      routes:
        - id: uploads-service
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

        - id: social-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stories/**, /api/v1/feed/**

        - id: marketplace-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/listings/**, /api/v1/bookings/**, /api/v1/reviews/**

        - id: subscription-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**, /api/payments/**, /api/v1/subscriptions/**

        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/direct-messages/**, /api/v1/messages/**

        - id: dating-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/dating/**

        - id: uploads-service
          uri: http://localhost:8082
          predicates:
            - Path=/uploads/**

server:
  port: 8000
