spring:
  application:
    name: hustleup-gateway
  codec:
    max-in-memory-size: 500MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
      routes:
        - id: uploads-service
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**,/api/v1/users

        - id: social-stories
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stories/**,/api/v1/stories

        - id: social-follows
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/follows/**,/api/v1/follows

        - id: social-feed
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/feed/**,/api/v1/feed

        - id: social-dating
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/dating/**,/api/v1/dating

        - id: marketplace-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/listings/**,/api/v1/bookings/**,/api/v1/reviews/**

        - id: subscription-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**,/api/payments/**,/api/v1/subscriptions/**

        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/notifications/**,/api/v1/direct-messages/**,/api/v1/messages/**



server:
  port: 8000
